// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDinWqhAqnZ7GRLgTnVOL1ba7oeWplpmoA',
    appId: '1:54615680615:web:8eaaf1a6f7b95dea1b96c2',
    messagingSenderId: '54615680615',
    projectId: 'quick-type-eafa3',
    authDomain: 'quick-type-eafa3.firebaseapp.com',
    databaseURL: 'https://quick-type-eafa3-default-rtdb.firebaseio.com',
    storageBucket: 'quick-type-eafa3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_8osQJ-H5wrS7g0thGCE6_ueVkDdVH0',
    appId: '1:54615680615:android:bfed9af90da6b18a1b96c2',
    messagingSenderId: '54615680615',
    projectId: 'quick-type-eafa3',
    databaseURL: 'https://quick-type-eafa3-default-rtdb.firebaseio.com',
    storageBucket: 'quick-type-eafa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9rPk9los597GzLTPu-KJepwlUyzp2D2s',
    appId: '1:54615680615:ios:33e59eef5b5c8d411b96c2',
    messagingSenderId: '54615680615',
    projectId: 'quick-type-eafa3',
    databaseURL: 'https://quick-type-eafa3-default-rtdb.firebaseio.com',
    storageBucket: 'quick-type-eafa3.appspot.com',
    androidClientId: '54615680615-vonmv4j6k4qhhdsv9uoaku7filhb3okk.apps.googleusercontent.com',
    iosClientId: '54615680615-fi29rdo4hfnajvnbks16g3fkji7h2akq.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickTakes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9rPk9los597GzLTPu-KJepwlUyzp2D2s',
    appId: '1:54615680615:ios:735dad22b6edc2801b96c2',
    messagingSenderId: '54615680615',
    projectId: 'quick-type-eafa3',
    databaseURL: 'https://quick-type-eafa3-default-rtdb.firebaseio.com',
    storageBucket: 'quick-type-eafa3.appspot.com',
    androidClientId: '54615680615-vonmv4j6k4qhhdsv9uoaku7filhb3okk.apps.googleusercontent.com',
    iosClientId: '54615680615-8d4aba7qc80euv8ce27qv2sfedi3hka9.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickTakes.RunnerTests',
  );
}
